# 服务器配置
server:
  port: 5002
  mode: debug # 可选：debug, release

# 数据库配置
database:
  host: 192.168.80.155
  port: 5432
  user: postgres
  password: 123456
  dbname: linkhub
  sslmode: disable

# JWT配置
jwt:
  secret: your-secret-key
  expire_hours: 168

# 网站配置
site:
  name: LinkHUB
  url: http://localhost:5002
  version: 0.1

# Google 登录配置
clientID: google登录客户端ID
clientSecret: google登录客户端密钥

geminiAPIKey: 你的Gemini API密钥

# 图床配置
upload:
  maxSize: 10485760
  allowedExts:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .webp
  imgurApiUrl: https://api.imgur.com/3/image
  imgurClientId: 123