# 服务器配置
server:
  port: 5002
  mode: debug # 可选：debug, release

# 数据库配置
database:
  host: 192.168.80.155
  port: 5432
  user: postgres
  password: 123456
  dbname: linkhub
  sslmode: disable

# JWT配置
jwt:
  secret: your-secret-key
  expire_hours: 24

# 网站配置
site:
  name: LinkHUB
  url: http://127.0.0.1:5002
  version: 0.1